### ISSUE TITLE
Support Neovim

### ISSUE THREAD

**Issue by iven** [shime/vim-livedown#18]
Seems broken in neovim, when calling `LivedownPreview`, only a blank page opens.

**Comment by RiderSargent** [comment]
Try visiting `http://localhost:1337` when you get the blank page. This worked for me. I think Chrome is actually refusing to load the local, rendered html file.

**Comment by iven** [comment]
It doesn't work. Actually I get the blank page when visiting `http://localhost:1337`.

**Comment by briandant** [comment]
> Try visiting http://localhost:1337 when you get the blank page. This worked for me. I think Chrome is actually refusing to load the local, rendered html file.

@RiderSargent: This happened to me, and it worked when I went directly to the page. Did you find a solution for Chrome -- can you get it to open automatically?

**Comment by shime** [comment]
Should be fixed now, I'll reopen if that's not the case.
