### ISSUE TITLE
`--browser` is now required?

### ISSUE THREAD

**Issue by john-kurkowski** [shime/vim-livedown#21]
Prior to #20, I could invoke `:LivedownPreview` without arguments, and my default browser, Chrome, would automatically pop open, showing the rendered document. Now, nothing seems to happen after `:LivedownPreview`. If I open [http://localhost:1337](http://localhost:1337) manually though, the rendered document is there.

Can optional flags like `--browser` be, well, optional?

**Comment by shime** [comment]
Closed in #23
