### ISSUE TITLE
livedown_browser option is not working

### ISSUE THREAD

**Issue by kopach** [shime/vim-livedown#25]
I'm trying to open markdown preview in some other browser, not default one (I have Chrome as default)

`let g:livedown_browser = "open /Applications/Safari.app"`
or
`let g:livedown_browser = "open /Applications/Chromium.app"
`
in my .vimrc not helping.

Does anybody know, maybe, why?

**Comment by shime** [comment]
Just published a new version, so please update with
```
npm install -g livedown
```

After that setting a browser to 
```
let g:livedown_browser = "safari"
```

should open Safari.
