### ISSUE TITLE
Doesn't recognize Google Chrome

### ISSUE THREAD

**Issue by Casinelli** [shime/vim-livedown#27]
Tried to switch to Google Chrome using:

```
let g:livedown_browser = "chrome"
```

And variations ("Chrome", "Google Chrome", "google chrome", etc.), but none works.

If I keep `safari` it works perfectly.

Is it a problem or am I doing something wrong?

**Comment by Casinelli** [comment]
@shime Tried now, doesn't work.

**Comment by shime** [comment]
What OS are you using?

**Comment by Casinelli** [comment]
MacOS Sierra version 10.12.5. Chrome version 60.

**Comment by shime** [comment]
Try with `'Google Chrome'`.

This opens google chrome on a Mac: 
```
$ livedown start README.md --browser "'Google Chrome'" --open
```

**Comment by Casinelli** [comment]
The console command works. But still not working in VIM. Tried both `:LivedownToggle` and `:LivedownPreview`, nothing.

**Comment by mengfankitty** [comment]
@Casinelli you can set the chrome as the default browser, then you no need to set the `g:livedown_browser`

**Comment by hitochan777** [comment]
`'google-chrome'` worked for me, though `livedown-autorun` and `livedown_open` are not working, so I have to call `:LivedownPreview` manually (and moreover I need to call this twice for the window to pop up!).
Btw, I am using ubuntu 16.04.

**Comment by justmendes** [comment]
This is fixed in #31 , if you're still having issues @Casinelli 

Since you're running Ubuntu, can you check @hitochan777 my version? To be sure it works in Linux before a fix is merged. Thanks!

**Comment by shime** [comment]
@hitochan777 please let me know if you still have issues with Chrome in Linux so I can reopen the issue if you do.

**Comment by hitochan777** [comment]
@justmendes @shime On Ubuntu, now `google-chrome` (not `'google-chrome'`) works! Thank you for your work!
Regarding `livedown-autorun` and `livedown_open` issue, it was due to the setting of vim package manager that I use.

By the way, it is a bit confusing to set different values depending on the OS (e.g., `chrome` and `google-chrome`).
It might be useful to mention the difference in the documentation.

**Comment by shime** [comment]
@hitochan777 great, thanks for the info.

Since Livedown uses [opn](https://github.com/sindresorhus/opn) for opening a browser, looks like you have an issue with that library. It looks like it uses some new version of `xdg-open` on Linux, so maybe that's the problem.

**Comment by justmendes** [comment]
@shime do you want me to change it to have a uniform option? Right now it's `google-chrome` on one OS, `chrome` on the other, which might be confusing.

**Comment by shime** [comment]
@justmendes yeah, go ahead. That would be great.
