### ISSUE TITLE
problems with TEMP files in Win8

### ISSUE THREAD

**Issue by yzatod** [shime/vim-livedown#5]
It seems that the plugin has a problem with creation of tempfiles. I am running Windows8.

Error detected while processing function LivedownPreview:
line 1:
E484: Cant open file c:\Users\HP\AppData\Local\Temp\VIoDD73.tmp

the temp file is missing in the Temp dir....
The problem persist if I change cygwin for cmd as shell.
please help

the problem is probably the same one that I had with vim gitgutter, which airblade (thanks) somehow solved (the problem disappered in newer commits, solution was not explicitely described)
https://github.com/airblade/vim-gitgutter/issues/206

**Comment by fruser** [comment]
@yzatod I am also getting this error message on my Windows 8.1 machine.

**Comment by bgshacklett** [comment]
I'm seeing this on Windows 10.
